-- Ejecutar estas sentencias en el Nodo 2 y en el Nodo 3 (servidores remotos reales)

-- 1. Si está GENERATED ALWAYS, primero debes eliminar la propiedad IDENTITY
ALTER TABLE orders
    ALTER COLUMN order_id DROP IDENTITY; 
    
-- 2. Añadir la propiedad IDENTITY con el modo "BY DEFAULT" (más flexible para FDW)
ALTER TABLE orders 
    ALTER COLUMN order_id ADD GENERATED BY DEFAULT AS IDENTITY; 

-- O, si solo quieres modificarla de ALWAYS a BY DEFAULT:
-- ALTER TABLE orders ALTER COLUMN order_id SET GENERATED BY DEFAULT;

-- Ejecutar este código en el NODO 2 y en el NODO 3 (servidores remotos)
CREATE OR REPLACE FUNCTION fn_insert_order_remote(p_customer_id VARCHAR(10))
RETURNS INT
LANGUAGE sql
AS $$
    -- El servidor remoto inserta el pedido y garantiza el ID
    INSERT INTO public.orders(customer_id, order_date)
    VALUES (p_customer_id, NOW())
    RETURNING order_id;
$$;